spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gestor_tareas_sabrosura?characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: Nada.es.verdad
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext