server:
  error:
    include-message: always
  port: 9011

spring:
  profiles:
    active: dev
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        maximum-pool-size: 5
        minimum-idle: 5
        connection-timeout: 30000
        idle-timeout: 600000
        max-lifetime: 1800000
        pool-name: "gestor-tareas-sabrodura"
      jpa:
        hibernate:
          ddl-auto: update
        properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect
            format_sql: true
            show_sql: true
            use_sql_comments: true
            current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
          show-sql: true
          database-platform: org.hibernate.dialect.MySQL5Dialect
      jackson:
        time-zone: America/Bogota
        date-format: yyyy-MM-dd HH:mm:ss